### ISSUE TITLE
[Feature] Ability to connect LinkedIn accounts

### ISSUE THREAD

**Issue by ajmeese7** [codersrank-org/libraries#132]
Hey guys, sorry that this probably isn't the right repo to make this issue at, but I'm not sure where the best place to make this suggestion is. Feel free to port this issue somewhere else if it would fit better there.

----

I would love to have the ability to have LinkedIn under "Connect your accounts", so my work experience and certifications and the like will stay synced up instead of being a one-time pull. I've noticed that my CodersRank profile is always out of date because I am constantly updating my LinkedIn and it is annoying to have to make all those changes twice. For now I've just deleted all my work experience from my CodersRank profile because it's much easier on me than keeping it up to date, but I would love to have this sync feature available on your platform in the future.

Thanks!

**Comment by krogucci** [comment]
hi @ajmeese7 thanks for reaching out. All feature requests should go to our Canny board: https://codersrank.canny.io/

That said, what you're requesting is definitely a functionality that we are currently considering as we feel users would benefit from it strongly. Stay in touch with our Canny board, Slack community and social media for any news around it :)

**Comment by ajmeese7** [comment]
Noted, thanks! Closing this out now :)
