### ISSUE TITLE
[Feature request] Add support for Enzyme Shallow

### ISSUE THREAD

**Issue by formidablae** [codersrank-org/libraries#134]
Enzyme, a JavaScript/TypeScript Testing utility for React, is already supported.
But sometimes it is imported as `'enzyme/shallow'` instead of `'enzyme'` .
It would be nice to have those imports (`'enzyme/shallow'`) recognised as Enzyme library usage.

**Comment by krogucci** [comment]
Thank you @formidablae - our devs will have a look at your two PRs soon.
