### ISSUE TITLE
[Feature request] Add support for sinon

### ISSUE THREAD

**Issue by formidablae** [codersrank-org/libraries#137]
Would be nice to have `sinon` as a recognised library.
`sinon` allows for standalone test spies, stubs and mocks in JavaScript.
Works with any unit testing framework.

**Comment by krogucci** [comment]
hi @formidablae! Thank you for the suggestion. I recommend adding it to our [Canny feedback board](https://codersrank.canny.io/) as it is the primary place where we gather feedback from our community, gather upvotes for certain ideas, etc. :)

**Comment by peti2001** [comment]
Hi, It has been added with this Pull Request: https://github.com/codersrank-org/libraries/pull/141

**Comment by formidablae** [comment]
> Hi, It has been added with this Pull Request: #141

Thank you :)
