### ISSUE TITLE
[Feature Request] Add Support for Flutter framework

### ISSUE THREAD

**Issue by rennylangat** [codersrank-org/libraries#142]
Flutter is now widely used and supported by enthusiastic cross-platform mobile developers -myself included - and I think it's a high time it was included.

**Comment by peti2001** [comment]
The library detection was missing for Dart. I have added it and now it can recognize `Flutter`. Please refresh your profile and you are supposed to see Flutter. 
And also feel free to suggest/add libraries for Dart.

**Comment by rennylangat** [comment]
Thanks a bunch
