### ISSUE TITLE
Add Svelte 

### ISSUE THREAD

**Issue by MarioDena** [codersrank-org/libraries#84]
It  would be nice if svelte was given a score or at least shown as a technology on the profile.

**Comment by StyvenSoft** [comment]
I have seen that this Framework is already added to the library:
```
"Svelte":{
      "imports":[
        "svelte"
      ],
      "technologies":[
        "Web Development",
        "SPA"
      ],
      "description":"Svelte is a radical new approach to building user interfaces. Whereas traditional frameworks like React and Vue do the bulk of their work in the browser, Svelte shifts that work into a compile step that happens when you build your app.",
      "image":"https://raw.githubusercontent.com/sveltejs/branding/master/svelte-logo.png"
    },
```
 And it is displayed with an epx score in the technology section of the profile.

**Comment by peti2001** [comment]
Hi @MarioDena,

Yes, it is added and it is visible on the profile too. For example here: https://profile.codersrank.io/user/nolimits4web.
I am closing it, but if you have any other issue. Feel free to open a new one.
