### ISSUE TITLE
Some questions 

### ISSUE THREAD

**Issue by zero734kr** [codersrank-org/libraries#91]
* Why is the list of TypeScript libraries shorter than the list of JavaScript if most libraries in js can also be used in ts?
* Extensions like ``jsx`` or ``tsx`` are also included in js or ts?

Thanks so much for a nice visual profile service.

**Comment by peti2001** [comment]
Hi @zero734kr,

Indeed, Js and Ts should be the same. It has been fixed and I added a rule to enforce it too.

Yes, we recognize `jsx` and `tsx`.
